import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Sidebar } from "./components/Sidebar";
import { Footer } from "./components/Footer";
import { auth } from "@/auth";
import localFont from "next/font/local";

const generalSans = localFont({
  src: [
    {
      path: "./fonts/GeneralSans-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-general-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Wishlist App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" className={generalSans.variable}>
      <body className="font-sans">
        <main className="h-screen flex flex-col w-full bg-[var(--color-bgbeige)]">
          <div className="flex">
            {session && (
              <div className="w-1/6">
                <Sidebar />
              </div>
            )}

            <div className={session ? "flex w-5/6 bg-[var(--color-bgbeige)] flex-col" : "w-full h-screen bg-[var(--color-bgbeige)] flex-col"}>
              <Navbar />
              <div>{children}</div>
            </div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
