import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Sidebar } from "./components/Sidebar";
import { Footer } from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <main className="h-screen flex flex-col w-full bg-[#FAF7F0]">
          <Navbar />
          <div className="flex">
            <div className="w-1/6">
              <Sidebar />
            </div>
            <div className="w-5/6 p-6 h-screen bg-[#FAF7F0]">{children}</div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
