import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Sidebar } from "./components/Sidebar";
import { Footer } from "./components/Footer";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wishlist App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <main className="h-screen flex flex-col w-full bg-[var(--color-bgbeige)]">
          <Navbar />
          <div className="flex">
            {session && (
              <div className="w-1/6">
                <Sidebar />
              </div>
            )}

            <div className={session ? "flex w-5/6 bg-[var(--color-bgbeige)]" : "w-full h-screen bg-[var(--color-bgbeige)]"}>{children}</div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
